from langchain_community.document_loaders import WebBaseLoader

url="https://www.flipkart.com/tyy/4io/~cs-1dvrypehdl/pr?sid=tyy%2C4io&collection-tab-name=Motorola+G85+5G&pageCriteria=default&param=1786&hpid=IlibjhUNTBf_2w7lAfhhU6p7_Hsxr70nj65vMAAFKlc%3D&ctx=eyJjYXJkQ29udGV4dCI6eyJhdHRyaWJ1dGVzIjp7InZhbHVlQ2FsbG91dCI6eyJtdWx0aVZhbHVlZEF0dHJpYnV0ZSI6eyJrZXkiOiJ2YWx1ZUNhbGxvdXQiLCJpbmZlcmVuY2VUeXBlIjoiVkFMVUVfQ0FMTE9VVCIsInZhbHVlcyI6WyJmcm9tIDE0OTk5KiJdLCJ2YWx1ZVR5cGUiOiJNVUxUSV9WQUxVRUQifX0sImhlcm9QaWQiOnsic2luZ2xlVmFsdWVBdHRyaWJ1dGUiOnsia2V5IjoiaGVyb1BpZCIsImluZmVyZW5jZVR5cGUiOiJQSUQiLCJ2YWx1ZSI6Ik1PQkhZOVBRN0ZHWktWREsiLCJ2YWx1ZVR5cGUiOiJTSU5HTEVfVkFMVUVEIn19LCJ0aXRsZSI6eyJtdWx0aVZhbHVlZEF0dHJpYnV0ZSI6eyJrZXkiOiJ0aXRsZSIsImluZmVyZW5jZVR5cGUiOiJUSVRMRSIsInZhbHVlcyI6WyJNb3Rvcm9sYSBHODUgNUciXSwidmFsdWVUeXBlIjoiTVVMVElfVkFMVUVEIn19fX19"

loader=WebBaseLoader(url)

docs=loader.load()

print(len(docs))

print(docs[0].page_content)